// Database types - would be auto-generated by Supabase CLI in production
// Run: supabase gen types typescript --local > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type SportType = 'tennis' | 'pickleball' | 'badminton' | 'padel';
export type TournamentStatus = 'draft' | 'registration' | 'in_progress' | 'completed' | 'cancelled';
export type TournamentFormat = 'single_elimination' | 'double_elimination' | 'round_robin' | 'swiss';
export type FixtureStatus = 'scheduled' | 'in_progress' | 'completed' | 'cancelled' | 'walkover';

export interface Database {
  public: {
    Tables: {
      organisations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      players: {
        Row: {
          id: string;
          user_id: string | null;
          display_name: string;
          email: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          display_name: string;
          email?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          display_name?: string;
          email?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      organisation_members: {
        Row: {
          id: string;
          organisation_id: string;
          player_id: string;
          role: 'owner' | 'admin' | 'scorer' | 'member';
          created_at: string;
        };
        Insert: {
          id?: string;
          organisation_id: string;
          player_id: string;
          role?: 'owner' | 'admin' | 'scorer' | 'member';
          created_at?: string;
        };
        Update: {
          id?: string;
          organisation_id?: string;
          player_id?: string;
          role?: 'owner' | 'admin' | 'scorer' | 'member';
          created_at?: string;
        };
      };
      tournaments: {
        Row: {
          id: string;
          organisation_id: string;
          name: string;
          slug: string;
          sport: SportType;
          format: TournamentFormat;
          status: TournamentStatus;
          is_doubles: boolean;
          scoring_config: Json;
          start_date: string | null;
          end_date: string | null;
          registration_deadline: string | null;
          max_participants: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organisation_id: string;
          name: string;
          slug: string;
          sport: SportType;
          format?: TournamentFormat;
          status?: TournamentStatus;
          is_doubles?: boolean;
          scoring_config?: Json;
          start_date?: string | null;
          end_date?: string | null;
          registration_deadline?: string | null;
          max_participants?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organisation_id?: string;
          name?: string;
          slug?: string;
          sport?: SportType;
          format?: TournamentFormat;
          status?: TournamentStatus;
          is_doubles?: boolean;
          scoring_config?: Json;
          start_date?: string | null;
          end_date?: string | null;
          registration_deadline?: string | null;
          max_participants?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tournament_players: {
        Row: {
          id: string;
          tournament_id: string;
          player_id: string;
          seed_number: number | null;
          registration_status: 'pending' | 'confirmed' | 'withdrawn';
          registered_at: string;
        };
        Insert: {
          id?: string;
          tournament_id: string;
          player_id: string;
          seed_number?: number | null;
          registration_status?: 'pending' | 'confirmed' | 'withdrawn';
          registered_at?: string;
        };
        Update: {
          id?: string;
          tournament_id?: string;
          player_id?: string;
          seed_number?: number | null;
          registration_status?: 'pending' | 'confirmed' | 'withdrawn';
          registered_at?: string;
        };
      };
      fixtures: {
        Row: {
          id: string;
          tournament_id: string;
          round_number: number;
          match_number: number;
          court_name: string | null;
          scheduled_time: string | null;
          status: FixtureStatus;
          winner_advances_to: string | null;
          loser_drops_to: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tournament_id: string;
          round_number: number;
          match_number: number;
          court_name?: string | null;
          scheduled_time?: string | null;
          status?: FixtureStatus;
          winner_advances_to?: string | null;
          loser_drops_to?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tournament_id?: string;
          round_number?: number;
          match_number?: number;
          court_name?: string | null;
          scheduled_time?: string | null;
          status?: FixtureStatus;
          winner_advances_to?: string | null;
          loser_drops_to?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      fixture_teams: {
        Row: {
          id: string;
          fixture_id: string;
          team_position: 1 | 2;
          is_winner: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          fixture_id: string;
          team_position: 1 | 2;
          is_winner?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          fixture_id?: string;
          team_position?: 1 | 2;
          is_winner?: boolean | null;
          created_at?: string;
        };
      };
      fixture_team_players: {
        Row: {
          id: string;
          fixture_team_id: string;
          player_id: string;
        };
        Insert: {
          id?: string;
          fixture_team_id: string;
          player_id: string;
        };
        Update: {
          id?: string;
          fixture_team_id?: string;
          player_id?: string;
        };
      };
      match_scores: {
        Row: {
          id: string;
          fixture_id: string;
          team1_sets_won: number;
          team2_sets_won: number;
          current_set_number: number;
          current_game_team1: number;
          current_game_team2: number;
          current_point_team1: string;
          current_point_team2: string;
          serving_team: 1 | 2 | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          fixture_id: string;
          team1_sets_won?: number;
          team2_sets_won?: number;
          current_set_number?: number;
          current_game_team1?: number;
          current_game_team2?: number;
          current_point_team1?: string;
          current_point_team2?: string;
          serving_team?: 1 | 2 | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          fixture_id?: string;
          team1_sets_won?: number;
          team2_sets_won?: number;
          current_set_number?: number;
          current_game_team1?: number;
          current_game_team2?: number;
          current_point_team1?: string;
          current_point_team2?: string;
          serving_team?: 1 | 2 | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      set_scores: {
        Row: {
          id: string;
          match_score_id: string;
          set_number: number;
          team1_games: number;
          team2_games: number;
          is_tiebreak: boolean;
          team1_tiebreak_points: number | null;
          team2_tiebreak_points: number | null;
          winner_team: 1 | 2 | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          match_score_id: string;
          set_number: number;
          team1_games?: number;
          team2_games?: number;
          is_tiebreak?: boolean;
          team1_tiebreak_points?: number | null;
          team2_tiebreak_points?: number | null;
          winner_team?: 1 | 2 | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          match_score_id?: string;
          set_number?: number;
          team1_games?: number;
          team2_games?: number;
          is_tiebreak?: boolean;
          team1_tiebreak_points?: number | null;
          team2_tiebreak_points?: number | null;
          winner_team?: 1 | 2 | null;
          completed_at?: string | null;
        };
      };
      score_events: {
        Row: {
          id: string;
          fixture_id: string;
          event_type: string;
          scoring_team: 1 | 2;
          score_snapshot: Json;
          recorded_by: string | null;
          recorded_at: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          fixture_id: string;
          event_type: string;
          scoring_team: 1 | 2;
          score_snapshot: Json;
          recorded_by?: string | null;
          recorded_at?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          fixture_id?: string;
          event_type?: string;
          scoring_team?: 1 | 2;
          score_snapshot?: Json;
          recorded_by?: string | null;
          recorded_at?: string;
          notes?: string | null;
        };
      };
    };
    Enums: {
      sport_type: SportType;
      tournament_status: TournamentStatus;
      tournament_format: TournamentFormat;
      fixture_status: FixtureStatus;
    };
  };
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
